name: make release

on:
  workflow_call:

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
      - name: get repo
        uses: actions/checkout@v6

      - name: Set short git commit SHA
        id: vars
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.SHORT_SHA }}

      - name: make tag
        run: |
          git tag origin ${{ env.SHORT_SHA }}
          git push origin

      - name: make release.txt
        run: echo ${{ env.SHORT_SHA }} > Release.txt

      - name: get action-gh-release
        uses: softprops/action-gh-release@v2
        with:
          files: Release.txt

