name: make release

on:
  workflow_call:

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
      - name: get repo
        uses: actions/checkout@v6

      - name: make tag
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GIT_SHA_LATEST
          git tag $GIT_SHA_LATEST $GIT_SHA_LATEST
          git push origin $GIT_SHA_LATEST

      - name: make release.txt
        run: echo $GIT_SHA_LATEST > Release.txt

      - name: get action-gh-release
        uses: softprops/action-gh-release@v2
        with:
          files: Release.txt

