# This is a basic workflow to help you get started with Actions

name: reusable_test
on: workflow_call

# Controls when the workflow will run
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  whats-good-js:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6

      # Runs a single command using the runners shell
      - run: node js-scripts/whats_good.js
