name: Reusable workflow example

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6

      - name: run code
        run: node js-scripts/whats_good.js

      - name: get upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: logging.js
          path: js-scripts/logging.js
          overwrite: true

